### PR TITLE
strictMode: true by default, false avoids throwing

### PR DESCRIPTION
**Pull request by philsturgeon**
Implements #33

### CODE REVIEW

**Comment by XVincentX** [comment]
@mikunn Any chance to get this merged/released?

**Comment by pytlesk4** [comment]
@philsturgeon looks good, maybe wrap [this](https://github.com/mikunn/openapi-schema-to-json-schema/blob/master/lib/converters/parameter.js#L13) line in an if statement as well?

```ts
if (options.strictMode) {
  throw new InvalidInputError('OpenAPI parameter must have either a \'schema\' or a \'content\' property');
}
```

**Comment by philsturgeon** [comment]
@pytlesk4 it is already, check the diff :D

**Comment by philsturgeon** [comment]
@mikunn ready when you are, can we get this merged and tagged this week?

**Comment by philsturgeon** [comment]
@mikunn hey man, can you help us out? We really need this PR merged and released. I think I had a bit of a hard time with formatting because your indentation was a bit "non standard" but if you can just merge this and fix it for me I'll be happy to donate $20 to your coffee/beer fund wherever that may be. Let me know!

**Comment by philsturgeon** [comment]
@mikunn MIIIIIIIIIKA

**Comment by philsturgeon** [comment]
What is going on @mikunn can you reply?

**Comment by philsturgeon** [comment]
tenor-pussinboots-please

**Comment by XVincentX** [comment]
I would confidently say that this is never going to happen unfortunately.

**Comment by philsturgeon** [comment]
Yeah I’ve been trying to avoid doing this but now have no choice. I’ve moved my fork to OpenAPI-Contrib https://github.com/openapi-contrib/openapi-schema-to-json-schema 

We’ll maintain it going forward and release it under our vendor namespace. Stoplight can use that one.

**Comment by philsturgeon** [comment]
Gave up. If anyone wants to switch to a maintained version, we're over here. https://github.com/openapi-contrib/openapi-schema-to-json-schema

**Comment by philsturgeon** [comment]
@mikunn I really hope everything is ok.

**Comment by mikunn** [comment]
Dear Phil Sturgeon and the whole community,

I am deeply sorry that I have miserably failed maintaining this library.

Due to work and chain of events with family, I simply have not had time or energy to give a thought on this. This library was started with the support of my previous company, but my current employee or myself have no need for this which has had its consequences.

Also, all the notifications got lost somewhere in the middle of the gazillion notifications from my company's different repos. But I should have let you know the status way earlier.

Thank you @philsturgeon for continuing with the maintenance of this library. I am certain the library is now in much better hands. I will figure out how to mark this repo as unmaintained and guide everyone to the new home if that is ok for you. 

Once again, sorry and thank you.

Wishing everyone all the best,
Mika

**Comment by philsturgeon** [comment]
@mikunn I completely understand, no hard feelings and I hope everything is ok.

It seems like we have a result here anyway. These packages should not need to live much longer as https://github.com/OAI/OpenAPI-Specification/pull/1977 was merged, but in the mean time I am happy to maintain things.

>  I will figure out how to mark this repo as unmaintained and guide everyone to the new home if that is ok for you.

Run this:

```
npm deprecate openapi-schema-to-json-schema "This package is no longer maintained. Use @openapi-contrib/openapi-schema-to-json-schema instead."
```

This will put a massive banner at the top:

Screen Shot 2020-01-20 at 13 25 50

Thanks again!

**Comment by mikunn** [comment]
Thanks @philsturgeon!

I'll add the banner soon. Everything has been sorted out now, but I still feel you probably have more motivation to maintain the package.

Glad to know that the OpenAPI and the JSON Schema specs are finally heading to the right direction closing the gaps. Working with this package always felt hacky. Good work with the PR!

Btw, I've read lots of REST and API related stuff in general from you during the last 3 years or so and learned a lot. So thanks for those!

Good luck with all the future endeavours!

**Pull request closed without merging**
